### ISSUE TITLE
Typo in hero function page of the 1.4 documentation

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/solarus-doc#1]
in function description for hero:get direction(), there is a " symbol in the remarks paragraph that shouldn't be there. Also present in set_direction(direction4), maybe a copy-paste ?

**Comment by christopho** [comment]
Already fixed in 1.5.
You can find the doc of the 1.5 development version here: http://www.solarus-games.org/doc/1.5/lua_api_hero.html#lua_api_hero_get_direction
Thanks for the report though, don't hesitate to open other issues if you find something else.
