### ISSUE TITLE
Misprints in enemy.set_invincible Lua API

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-doc#24]
Misprints here:
http://www.solarus-games.org/doc/1.6/lua_api_enemy.html#lua_api_enemy_set_invincible
in both "enemy:set_invincible()" and "enemy:set_invincible_sprite(sprite)", where it says:
lua_api_enemy_set_attack_consequence(attack, "ignored")
and
lua_api_enemy_set_attack_consequence_sprite(sprite, attack, "ignored")

**Comment by christopho** [comment]
Fixed
